### PR TITLE
feat(maps): prefix/suffix badges and grouping on map mods page

### PR DESCRIPTION
**Pull request by SebRogala**
Reworked from #364 against the new `prefix: boolean` field on `MapModsTokenOption` (added in 1748c2bf935a72e5ec3af0b2286caaa1c1fbcf0d). No more sidecar — reads `token.options.prefix` directly.

## Summary

- Two new toggles in the Maps page options area:
  - **Show prefix/suffix badges** — fixed-width red `P` / blue `S` chip on each row (trade-style)
  - **Group mods by prefix/suffix** — `Prefix` / `Suffix` section headers inside each of the two existing columns
- Toggles are independent — either can be on alone.
- Search filter still runs before grouping; empty groups are hidden.
- No change to regex output. Purely visual.
- Toggle state persists via saved settings (defaults `false` — existing profiles keep current behavior).

## Implementation

- `SelectableTokenList` gets two optional extension points: `tagFn(token)` for a per-row badge and `groupFn(token)` + `groupOrder` for sectioning.
- `OptimizedMapMods.tsx` wires those to `token.options.prefix`. Tag/group functions are memoized so disabled toggles produce no extra work.
- New unit tests for `SelectableTokenList` cover tagFn, groupFn, group order, search-then-group, and selection toggling.

## Test plan

- [x] `npm test` — 5/5 pass
- [x] `npx tsc --noEmit` clean
- [x] Manual: toggles work independently, search filters under grouping, regex output unchanged, settings persist across reload

### CODE REVIEW

**Comment by veiset** [comment]
image

The tests doesn't run.

**Comment by veiset** [comment]
The code looks good, I like the design. 

Can you put the selection of prefixes / sorting above the option for nightmare mods?

**Comment by SebRogala** [comment]
- Toggle order — moved prefix/suffix above the nightmare-mods toggle.
- Tests not running — root cause was that `@types/testing-library__jest-dom` was only a transitive dep in `lockfile`, so installs that resolve the tree differently end up without the matcher type augmentation. Reproduced your exact `Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement>'` errors locally by removing the package, then promoted it to an explicit `devDependency` to guarantee it's always installed. Tests pass cleanly with `npm install && npm test`.

Let me know if anything else needs tweaking.

**Review by veiset — APPROVED** [review]
Thanks! Looks good, merging it. Should be live in ~5 mins
